# Generated by Django 5.2.12 on 2026-04-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paineladmin", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mural",
        ),
    ]
