# Generated by Django 6.0 on 2026-04-19 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mural',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='mural',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mural_main', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mural',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
